---
- name: Make sure we have the needed network manager libs
  package:
    name:
      - NetworkManager-glib
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present

- name: Make sure the network is configured as we expect it to be (NetworkManager)
  block:
    - name: "Ensure we added {{ }} for the SIPI"
      nmcli:
        conn_name: '{{ SIPI }}'
        type: "{{ sipi_team_mode }}"