---
- name: Configure eSDS host
  hosts:  "{{ node_name }}"
  become: true
  tasks:
          #  - name: Setup pre-installation requirements
          #include_role:
          #name: /root/git/internal-sds-host-config/roles/internal_sds_host_config
   
          #- name: Install eSDS software
          #    include_role:
          # name: /root/git/nar_solidfire_sds_install

  - name: Setup eSDS cluster
    include_role:
       name: /root/git/nar_solidfire_cluster_config
     
     
     
     
     
     
     
     
       # - role: nar_solidfire_sds_compliance
          # - role: nar_solidfire_sds_install
          #- role: nar_solidfire_cluster_config
    # - role: nar_solidfire_sds_upgrade
    #   - role: nar_solidfire_sds_uninstall
    
