## Import task for sds host config

- name: Execute task to verify NIC variables
  import_tasks: verify-nic-variables.yml

- name: Install required packages
  import_tasks: install_packages.yml

- name: Configure network 
  import_tasks: configure_network.yml

- name: Reboot host after network changes
  import_tasks: reboot_and_update_host.yml
