
- name: Reboot after network changes applied
  reboot:
    msg: "Reboot initiated by Ansible"
    post_reboot_delay: 30
    test_command: whoami

- name: Update ansible facts with host IP
  set_fact:
    ansible_ssh_host: "{{ hostvars[inventory_hostname].vars.MIP }}"

#- name: Wait for server to be up on new IP
#  wait_for_connection:
#    delay: 30
#    timeout: 330