- set_fact:
    sf_final_status: "unknown"
    sf_final_cluster_version: "unknown"
    sf_cluster_member_list: []

- name: Ensure all required variables are available
  include_tasks: prechecks.yml

- name: Ensure we load the set-cluster-name tasks
  include_tasks: set-cluster-name.yml

- name: Ensure we load the create-cluster tasks
  include_tasks: create-cluster.yml

- name: Ensure we add all available drives
  when: sf_auto_add_available_drives is undefined or
    (sf_auto_add_available_drives is defined and sf_auto_add_available_drives)
  include_tasks: add-drives.yml

- debug:
    msg: "Cluster creation was successful. Current cluster version: {{ sf_final_cluster_version }}. Please go to https://{{ MVIP }} to check any cluster alerts."
  when: sf_final_status == "success"
  run_once: True
